### ISSUE TITLE
Dimensions seem to prefer columns to the right

### ISSUE THREAD

**Issue by danqing** [novascreen/react-columns#28]
Thanks for this great library. I observed that when using dimensions, the last row usually has blank space in the left-most column (or columns to the left), whereas it should be the other way around (leaving the right-most column empty). This is the natural order.

Can this be changed? Thanks!

**Comment by novascreen** [comment]
Hi @danqing could you please attach a screenshot? This could just be coincidence, so that your right column is the shortest before adding the last image. In that case I don't think much can be done. To intervene manually you could play with the dimensions. For example if you pretend the second last item is higher than it actually is, your last item might be pushed to a different column. Does that make sense?

**Comment by danqing** [comment]
Thanks for the reply @novascreen ! That makes sense.

https://www.danqing.co/portfolio/studio-portraits/daven <- for example this link, when there are 3 columns the last row has it on the right.

I think it may make sense if there can be a bigger "tolerance", i.e. if the diff is < 5px say, prefer the left column. I'm not sure if that's easy to implement.

At any rate, thanks for the work!

**Comment by novascreen** [comment]
hey @danqing I had a look at your example and my code as well. I don't see a quick fix for that in the code. Your images are really big and 5px might still not do anything. In your use case the images appear to be all the same size, but are actually slightly different. If you would make them the exact same size the last image should appear on the left.
You don't even necessarily have to change the images. You could calculate an approximate aspect ratio for one of the images and then pass that in to all dimensions (e.g. 2:3 aspect ratio -> `width: 2, height: 3`).
Hope that helps.
If you want to dig into the code and propose a solution or create a PR I'm open to that, but will close this issue.
